name: Hugo Static Analysis

on: push
  # pull_request:
  #   types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  template-lint:
    name: Lint Hugo Templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install djLint
        run: pip install djlint

      - name: Lint layouts
        run: |
          echo "## ðŸŽ¨ Template Analysis" >> message.txt
          djlint layouts/ >> message.txt

      - uses: mshick/add-pr-comment@v2
        with:
          message-path: message.txt