name: Test with example

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set new submodule in new branch on Osuny Example
        uses: actions/checkout@v4
        with:
          repository: noesya/osuny-example
          submodules: 'recursive'
          token: ${{ secrets.OSUNY_EXAMPLE_TOKEN }}
      - name: Create new branch on Example
        run: |
          git config user.name osuny-bot
          git config user.email osuny@noesya.coop
          echo "== Creating new branch =="
          git checkout -b theme--${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
      - name: Checkout submodule
        uses: actions/checkout@v4
        with:
          repository: noesya/osuny-hugo-theme-aaa
          token: ${{ secrets.OSUNY_EXAMPLE_TOKEN }}
          path: themes/osuny-hugo-theme-aaa
          ref: ${{ github.head_ref || github.ref_name }}
      - name: Pushing new branch on Example
        run: |
          echo "== Pushing branch =="
          git add .
          git commit -m "Updated theme to ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} branch."
          git push -f origin theme--${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}